server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/EasyHouseRent?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    database: 0
    host: localhost
    port: 6379
#mybatis:
#  mapper-locations: com/dy/details/dao/**/*.xml
#  type-aliases-package: com.dy.details.pojo
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#logging:
#  level:
#    com.lucifer.springboot.cache.mapper: debug